<a href="https://colab.research.google.com/github/nikhilongo/Playground-datasets/blob/main/spaceship_titanic/spaceship_titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('train.csv')

In [ ]:
df.shape

(8693, 11)

In [ ]:
df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    8492 non-null   object
 1   CryoSleep     8476 non-null   object
 2   Destination   8511 non-null   object
 3   Age           8514 non-null   float64
 4   VIP           8490 non-null   object
 5   RoomService   8512 non-null   float64
 6   FoodCourt     8510 non-null   float64
 7   ShoppingMall  8485 non-null   float64
 8   Spa           8510 non-null   float64
 9   VRDeck        8505 non-null   float64
 10  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(4)
memory usage: 687.8+ KB

In [ ]:
[df[col].value_counts() for col in df]

[PassengerId
 9280_02    1
 0001_01    1
 0002_01    1
 0003_01    1
 0003_02    1
           ..
 0020_04    1
 0020_05    1
 0020_06    1
 0022_01    1
 0024_01    1
 Name: count, Length: 8693, dtype: int64,
 HomePlanet
 Earth     4602
 Europa    2131
 Mars      1759
 Name: count, dtype: int64,
 CryoSleep
 False    5439
 True     3037
 Name: count, dtype: int64,
 Cabin
 G/734/S     8
 B/11/S      7
 F/1411/P    7
 B/82/S      7
 G/981/S     7
            ..
 G/543/S     1
 B/106/P     1
 G/542/S     1
 F/700/P     1
 G/559/P     1
 Name: count, Length: 6560, dtype: int64,
 Destination
 TRAPPIST-1e      5915
 55 Cancri e      1800
 PSO J318.5-22     796
 Name: count, dtype: int64,
 Age
 24.0    324
 18.0    320
 21.0    311
 19.0    293
 23.0    292
        ...
 72.0      4
 78.0      3
 79.0      3
 77.0      2
 76.0      2
 Name: count, Length: 80, dtype: int64,
 VIP
 False    8291
 True      199
 Name: count, dtype: int64,
 RoomService
 0.0       5577
 1.0        117
 2.0         79
 3.0         61
 4.0         47
           ...
 903.0        1
 1032.0       1
 726.0        1
 1186.0       1
 3551.0       1
 Name: count, Length: 1273, dtype: int64,
 FoodCourt
 0.0       5456
 1.0        116
 2.0         75
 4.0         53
 3.0         53
           ...
 3462.0       1
 2651.0       1
 399.0        1
 2524.0       1
 1470.0       1
 Name: count, Length: 1507, dtype: int64,
 ShoppingMall
 0.0       5587
 1.0        153
 2.0         80
 3.0         59
 4.0         45
           ...
 624.0        1
 251.0        1
 1353.0       1
 184.0        1
 1296.0       1
 Name: count, Length: 1115, dtype: int64,
 Spa
 0.0       5324
 1.0        146
 2.0        105
 5.0         53
 3.0         53
           ...
 3668.0       1
 4125.0       1
 7967.0       1
 799.0        1
 753.0        1
 Name: count, Length: 1327, dtype: int64,
 VRDeck
 0.0       5495
 1.0        139
 2.0         70
 3.0         56
 5.0         51
           ...
 848.0        1
 1972.0       1
 1964.0       1
 4435.0       1
 1547.0       1
 Name: count, Length: 1306, dtype: int64,
 Name
 Ankalik Nateansive    2
 Gwendy Sykess         2
 Cuses Pread           2
 Keitha Josey          2
 Glenna Valezaley      2
                      ..
 Backse Cla            1
 Fres Cla              1
 Dous Blane            1
 Spies Gency           1
 Aliey Chanash         1
 Name: count, Length: 8473, dtype: int64,
 Transported
 True     4378
 False    4315
 Name: count, dtype: int64]

In [ ]:
df.drop(columns=['PassengerId','Cabin','Name'],inplace=True)

In [ ]:
df.isnull().sum().reset_index()

           index    0
0     HomePlanet  201
1      CryoSleep  217
2    Destination  182
3            Age  179
4            VIP  203
5    RoomService  181
6      FoodCourt  183
7   ShoppingMall  208
8            Spa  183
9         VRDeck  188
10   Transported    0

In [ ]:
df[df['CryoSleep'].isnull()]

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
92,Earth,NaN,TRAPPIST-1e,2.0,False,0.0,0.0,0.0,0.0,0.0,True
98,Earth,NaN,TRAPPIST-1e,27.0,False,0.0,0.0,570.0,2.0,131.0,False
104,Europa,NaN,TRAPPIST-1e,40.0,False,0.0,331.0,0.0,0.0,1687.0,False
111,Mars,NaN,TRAPPIST-1e,26.0,False,0.0,0.0,0.0,0.0,NaN,True
152,Earth,NaN,TRAPPIST-1e,58.0,False,0.0,985.0,0.0,5.0,0.0,True
...,...,...,...,...,...,...,...,...,...,...,...
8620,Europa,NaN,55 Cancri e,44.0,False,0.0,0.0,0.0,0.0,0.0,True
8651,Earth,NaN,TRAPPIST-1e,8.0,False,0.0,0.0,0.0,0.0,0.0,False
8664,Earth,NaN,TRAPPIST-1e,32.0,False,0.0,0.0,0.0,0.0,0.0,True
8675,Earth,NaN,TRAPPIST-1e,44.0,False,1030.0,1015.0,0.0,11.0,NaN,True
8687,Europa,NaN,TRAPPIST-1e,30.0,False,0.0,3208.0,0.0,2.0,330.0,True

In [ ]:
col=[col for col in df if df[col].dtypes=='float64']
for i in col:
    df[i].fillna(df[i].mean(),inplace=True)

<ipython-input-25-a625f6ec4303>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].mean(),inplace=True)

In [ ]:
col1=[col1 for col1 in df if df[col1].dtypes=='object']
for i in col1:
    df[i].fillna(df[i].mode()[0],inplace=True)

<ipython-input-27-6322970d6208>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].mode()[0],inplace=True)
<ipython-input-27-6322970d6208>:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[i].fillna(df[i].mode()[0],inplace=True)

In [ ]:
df.isnull().sum()

HomePlanet      0
CryoSleep       0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Transported     0
dtype: int64

In [ ]:
df1 = pd.get_dummies(df,columns=col1,drop_first=True)

In [ ]:
y = df['Transported']

In [ ]:
x = df1.drop(columns=['Transported'])

In [ ]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
x_flatten = sc.fit_transform(x)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_flatten,y,test_size=0.3)

In [ ]:
x_train.shape

(6085, 12)

In [ ]:
import tensorflow as tf
import tensorflow.keras as k
from keras.models import Sequential

In [ ]:
model = Sequential([
    k.layers.Dense(24,input_shape=(12,),activation='relu'),
    k.layers.Dense(12,activation='relu'),
    k.layers.Dense(1,activation='sigmoid')
])
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_flatten,y,epochs=100)

Epoch 1/100

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

272/272 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6784 - loss: 0.6319
Epoch 2/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7435 - loss: 0.5319
Epoch 3/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7552 - loss: 0.5022
Epoch 4/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7656 - loss: 0.4707
Epoch 5/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7748 - loss: 0.4575
Epoch 6/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7743 - loss: 0.4594
Epoch 7/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7849 - loss: 0.4424
Epoch 8/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7804 - loss: 0.4434
Epoch 9/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7895 - loss: 0.4366
Epoch 10/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7951 - loss: 0.4374
Epoch 11/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7948 - loss: 0.4376
Epoch 12/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7905 - loss: 0.4437
Epoch 13/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7850 - loss: 0.4373
Epoch 14/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7955 - loss: 0.4374
Epoch 15/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7825 - loss: 0.4389
Epoch 16/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7902 - loss: 0.4349
Epoch 17/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7852 - loss: 0.4406
Epoch 18/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8018 - loss: 0.4238
Epoch 19/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8015 - loss: 0.4209
Epoch 20/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7902 - loss: 0.4385
Epoch 21/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7932 - loss: 0.4316
Epoch 22/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7882 - loss: 0.4355
Epoch 23/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7868 - loss: 0.4388
Epoch 24/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7930 - loss: 0.4367
Epoch 25/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7933 - loss: 0.4327
Epoch 26/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7937 - loss: 0.4332
Epoch 27/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7976 - loss: 0.4195
Epoch 28/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7921 - loss: 0.4341
Epoch 29/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8007 - loss: 0.4284
Epoch 30/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7969 - loss: 0.4261
Epoch 31/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7919 - loss: 0.4353
Epoch 32/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7872 - loss: 0.4405
Epoch 33/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7972 - loss: 0.4296
Epoch 34/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7974 - loss: 0.4340
Epoch 35/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7939 - loss: 0.4296
Epoch 36/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7894 - loss: 0.4344
Epoch 37/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7943 - loss: 0.4271
Epoch 38/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8009 - loss: 0.4256
Epoch 39/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7966 - loss: 0.4325
Epoch 40/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8021 - loss: 0.4230
Epoch 41/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7985 - loss: 0.4202
Epoch 42/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7923 - loss: 0.4311
Epoch 43/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7965 - loss: 0.4285
Epoch 44/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8024 - loss: 0.4198
Epoch 45/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7940 - loss: 0.4286
Epoch 46/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7978 - loss: 0.4279
Epoch 47/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7973 - loss: 0.4279
Epoch 48/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7917 - loss: 0.4236
Epoch 49/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7985 - loss: 0.4208
Epoch 50/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7898 - loss: 0.4306
Epoch 51/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8013 - loss: 0.4183
Epoch 52/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8048 - loss: 0.4136
Epoch 53/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8040 - loss: 0.4198
Epoch 54/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8008 - loss: 0.4270
Epoch 55/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7988 - loss: 0.4279
Epoch 56/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7994 - loss: 0.4235
Epoch 57/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7932 - loss: 0.4254
Epoch 58/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7975 - loss: 0.4305
Epoch 59/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7960 - loss: 0.4226
Epoch 60/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8020 - loss: 0.4230
Epoch 61/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7946 - loss: 0.4263
Epoch 62/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8034 - loss: 0.4243
Epoch 63/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7960 - loss: 0.4269
Epoch 64/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7934 - loss: 0.4302
Epoch 65/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8017 - loss: 0.4169
Epoch 66/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7992 - loss: 0.4272
Epoch 67/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7997 - loss: 0.4160
Epoch 68/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7996 - loss: 0.4244
Epoch 69/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7961 - loss: 0.4297
Epoch 70/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8066 - loss: 0.4158
Epoch 71/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8006 - loss: 0.4231
Epoch 72/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8005 - loss: 0.4236
Epoch 73/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8016 - loss: 0.4195
Epoch 74/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7878 - loss: 0.4387
Epoch 75/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7967 - loss: 0.4202
Epoch 76/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7951 - loss: 0.4235
Epoch 77/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7928 - loss: 0.4306
Epoch 78/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8083 - loss: 0.4154
Epoch 79/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7991 - loss: 0.4193
Epoch 80/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7947 - loss: 0.4243
Epoch 81/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7949 - loss: 0.4265
Epoch 82/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8049 - loss: 0.4176
Epoch 83/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7939 - loss: 0.4243
Epoch 84/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8008 - loss: 0.4284
Epoch 85/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7983 - loss: 0.4244
Epoch 86/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8017 - loss: 0.4185
Epoch 87/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7969 - loss: 0.4237
Epoch 88/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8067 - loss: 0.4178
Epoch 89/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8048 - loss: 0.4161
Epoch 90/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7994 - loss: 0.4195
Epoch 91/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7995 - loss: 0.4231
Epoch 92/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8053 - loss: 0.4184
Epoch 93/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8044 - loss: 0.4171
Epoch 94/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7920 - loss: 0.4286
Epoch 95/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7943 - loss: 0.4187
Epoch 96/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7973 - loss: 0.4188
Epoch 97/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8034 - loss: 0.4134
Epoch 98/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7918 - loss: 0.4300
Epoch 99/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8021 - loss: 0.4265
Epoch 100/100
272/272 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8000 - loss: 0.4190

In [ ]:
model.evaluate(x_test,y_test)

82/82 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7836 - loss: 0.4366

[0.42296403646469116, 0.796012282371521]

In [ ]:
predict = model.predict(x_test)

82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [ ]:
predict[2]

array([0.08461315], dtype=float32)

In [ ]:
predicted = []
for i in predict:
  if(i>0.5):
    predicted.append(1)
  else:
    predicted.append(0)

In [ ]:
tf.math.confusion_matrix(y_test,predicted)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1025,  271],
       [ 283, 1029]], dtype=int32)>

In [ ]:
test = pd.read_csv('test.csv')

In [ ]:
PassengerId = test['PassengerId']
test.drop(columns=['PassengerId','Cabin','Name'],inplace=True)

In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    4190 non-null   object
 1   CryoSleep     4184 non-null   object
 2   Destination   4185 non-null   object
 3   Age           4277 non-null   float64
 4   VIP           4184 non-null   object
 5   RoomService   4277 non-null   float64
 6   FoodCourt     4277 non-null   float64
 7   ShoppingMall  4277 non-null   float64
 8   Spa           4277 non-null   float64
 9   VRDeck        4277 non-null   float64
dtypes: float64(6), object(4)
memory usage: 334.3+ KB

In [ ]:
test.isnull().sum()

HomePlanet       87
CryoSleep        93
Destination      92
Age              91
VIP              93
RoomService      82
FoodCourt       106
ShoppingMall     98
Spa             101
VRDeck           80
dtype: int64

In [ ]:
col10=[col10 for col10 in test if test[col10].dtypes=='float64']
for i in col10:
    test[i].fillna(test[i].mean(),inplace=True)

<ipython-input-69-3f4028301a18>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test[i].fillna(test[i].mean(),inplace=True)

In [ ]:
col11=[col11 for col11 in test if test[col11].dtypes=='object']
for i in col11:
    test[i].fillna(test[i].mode()[0],inplace=True)

<ipython-input-73-9e597fd006e2>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test[i].fillna(test[i].mode()[0],inplace=True)
<ipython-input-73-9e597fd006e2>:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test[i].fillna(test[i].mode()[0],inplace=True)

In [ ]:
test1 = pd.get_dummies(test,columns=col11,drop_first=True)

In [ ]:
test1_flatten = sc.fit_transform(test1)

In [ ]:
Transport=model.predict(test1_flatten)

134/134 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [ ]:
Transported = []
for i in Transport:
  if(i>0.5):
    Transported.append(1)
  else:
    Transported.append(0)

In [ ]:
Transported = pd.DataFrame(Transported)

In [ ]:
pd.concat([PassengerId,Transported],axis=1).to_csv("submission.csv",index=False)